// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4N_kCmN94r7aYy-HXPTgFTWkn_nZvATQ',
    appId: '1:264034235970:web:d09d8c05c6fa1a9bc19fdb',
    messagingSenderId: '264034235970',
    projectId: 'buic-app',
    authDomain: 'buic-app.firebaseapp.com',
    databaseURL: 'https://buic-app-default-rtdb.firebaseio.com',
    storageBucket: 'buic-app.appspot.com',
    measurementId: 'G-YXY0YC4M63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnjcENSTlvTdxHjHFa0nTequ-NkGCJAC4',
    appId: '1:264034235970:android:5eeccc44a6a07219c19fdb',
    messagingSenderId: '264034235970',
    projectId: 'buic-app',
    databaseURL: 'https://buic-app-default-rtdb.firebaseio.com',
    storageBucket: 'buic-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGmFcpWImNjWSjg5s0y7-PuVwQ5IwfD0',
    appId: '1:264034235970:ios:d49d34603265922cc19fdb',
    messagingSenderId: '264034235970',
    projectId: 'buic-app',
    databaseURL: 'https://buic-app-default-rtdb.firebaseio.com',
    storageBucket: 'buic-app.appspot.com',
    androidClientId: '264034235970-jleg6eg9jidd5phd6tccgb4mkkbq5dk5.apps.googleusercontent.com',
    iosClientId: '264034235970-3138q2jspiicnq8tbj5ooa2nasc03tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.buicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGmFcpWImNjWSjg5s0y7-PuVwQ5IwfD0',
    appId: '1:264034235970:ios:d49d34603265922cc19fdb',
    messagingSenderId: '264034235970',
    projectId: 'buic-app',
    databaseURL: 'https://buic-app-default-rtdb.firebaseio.com',
    storageBucket: 'buic-app.appspot.com',
    androidClientId: '264034235970-jleg6eg9jidd5phd6tccgb4mkkbq5dk5.apps.googleusercontent.com',
    iosClientId: '264034235970-3138q2jspiicnq8tbj5ooa2nasc03tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.buicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4N_kCmN94r7aYy-HXPTgFTWkn_nZvATQ',
    appId: '1:264034235970:web:80c1be252256d535c19fdb',
    messagingSenderId: '264034235970',
    projectId: 'buic-app',
    authDomain: 'buic-app.firebaseapp.com',
    databaseURL: 'https://buic-app-default-rtdb.firebaseio.com',
    storageBucket: 'buic-app.appspot.com',
    measurementId: 'G-334BVDLHPS',
  );
}
